### ISSUE TITLE
TypeError: compiler.getInfrastructureLogger is not a function

### ISSUE THREAD

**Issue by JackieChanWang** [gregnb/filemanager-webpack-plugin#91] opened 2021-01-20 08:07 UTC
## Config

```js
const FileManagerPlugin = require('filemanager-webpack-plugin')
module.exports = {
  plugins: [
   new FileManagerPlugin({
      events: {
        // onStart: {
        //     delete: './dist/demo.zip'
        // },
        onEnd: {
            mkdir: ['./dist'], // 新加的一句代码
            delete: [
                './dist/demo.zip',
            ],
           archive: [
                {source: './dist', destination: './dist/demo.zips'},
            ]
        }
      }
   })
 ]
}
```

## Issue
```
building for production...E:\2018_year\b2b-base\node_modules\filemanager-webpack-plugin\lib\index.js:577
    this.logger = compiler.getInfrastructureLogger(PLUGIN_NAME);
                           ^

TypeError: compiler.getInfrastructureLogger is not a function
    at FileManagerPlugin.apply (E:\2018_year\b2b-base\node_modules\filemanager-webpack-plugin\lib\index.js:577:28)
    at Compiler.apply (E:\2018_year\b2b-base\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (E:\2018_year\b2b-base\node_modules\webpack\lib\webpack.js:33:19)
    at E:\2018_year\b2b-base\build\build.js:19:5
    at next (E:\2018_year\b2b-base\node_modules\rimraf\rimraf.js:75:7)
    at CB (E:\2018_year\b2b-base\node_modules\rimraf\rimraf.js:111:9)
    at E:\2018_year\b2b-base\node_modules\rimraf\rimraf.js:137:14
    at FSReqCallback.oncomplete (fs.js:158:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iec-b2b-manager@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iec-b2b-manager@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |    3.1.0     |
| node                       |      12.14.1   |
| OS                         |    win10     |

**Comment by JackieChanWang** [comment] 2021-01-20 08:08
Import plug-in package to report error

**Comment by zhizunbaono1** [comment] 2021-04-13 03:39
Do you solve the problem

**Comment by sibiraj-s** [comment] 2021-04-13 05:11
Sorry. I missed to reply here. This seems to be not a problem with the plugin. Might be related to https://github.com/webpack/webpack/issues/9553.

The problem seems to be around having multiple versions installed. Try removing `node_modules` and `yarn.lock` and reinstall. That might work.

**Comment by chenyjyoucan** [comment] 2021-05-31 08:42
Your method doesn't seem to solve the problem

**Comment by jaredloomis** [comment] 2021-07-02 20:49
For myself, this issue was due to having a global **and** a local install of webpack. using `$(yarn bin webpack)` instead of `webpack` did the trick.

**Comment by sibiraj-s** [comment] 2021-07-04 01:34
Thanks @jaredloomis for sharing.

**Comment by sibiraj-s** [comment] 2021-07-07 02:08
Closing since the issue is not related to the plugin.

**Closed by sibiraj-s** 2021-07-07 02:08 UTC

**Comment by miaolin1993** [comment] 2023-02-13 06:41
所以这个问题要如何解决，我是升级webpack5后遇到的

**Comment by kiraraty** [comment] 2023-02-15 11:43
> 所以这个问题要如何解决，我是升级webpack5后遇到的
我也出现问题了 easywebpack  应该是cli不匹配问题
