### ISSUE TITLE
How to package dist to realize dual directory

### ISSUE THREAD

**Issue by xqhmz** [gregnb/filemanager-webpack-plugin#115] opened 2022-03-23 06:18 UTC
How to package dist to realize dual directory
 example:
dist.zip/dist/css

![image](https://user-images.githubusercontent.com/49462898/159635811-82a3a7ee-69e9-466a-99c0-c8105c1325d3.png)

**Comment by sibiraj-s** [comment] 2022-03-26 04:45
Can you elaborate? I couldn't understand whats needed.

**Comment by xqhmz** [comment] 2022-04-08 06:07
> Can you elaborate? I couldn't understand whats needed.

Vue dist compressed package with dist folder

**Comment by sibiraj-s** [comment] 2022-04-09 05:58
Screenshots are not helpful. Please describe with some detail.

**Comment by daoxincc** [comment] 2022-04-15 02:03
Maybe he means that he wants to remove the dist directory from the zip package and only package the dist subdirectory

**Comment by xqhmz** [comment] 2022-04-15 02:21
> 



> Maybe he means that he wants to remove the dist directory from the zip package and only package the dist subdirectory


On the contrary,I hope package  the dist directory  and  the dist subdirectory，now it dose not has the dist directory only has 
the dist subdirectory

`const FileManagerPlugin = require('filemanager-webpack-plugin');
const path = require("path");

module.exports = {
   configureWebpack:{
       resolve:{
          extensions:['.js', '.json', '.vue', '.scss', '.css'],
          alias: {
              "@": path.resolve(__dirname, "./src"),
              "@c": path.resolve(__dirname, "./src/common")
          }
       }
       plugins:[
          new FileManagerPlugin({
             onEnd:{
                delete:["./dist.zip"],
                archive:[{source: "./dist", destination: "./dist.zip"}]
             }
          })
       ]
   }
}`

**Comment by daoxincc** [comment] 2022-04-15 02:36
cool, it works

**Comment by daoxincc** [comment] 2022-04-15 02:37
I think that's his want

**Comment by sibiraj-s** [comment] 2022-05-07 08:04
Ah. That was the intended behaviour. If you want  source directory to be a part of the output archive as well. then you could move it into another directory and zip that.

**Comment by parkerisme** [comment] 2022-06-29 11:29
Ah.I want it also.so what should i do?the mthod move is not easy.

**Comment by Sherrychen1** [comment] 2023-05-05 08:58
> 
![99](https://user-images.githubusercontent.com/27287643/236416881-1f9ab8fe-52c8-4b63-b010-b02077fe02d6.jpg)


我想压缩后保留dist目录以及子文件，但是不行

**Comment by joket1999** [comment] 2023-06-17 09:08
> > 
> 
> ![99](https://user-images.githubusercontent.com/27287643/236416881-1f9ab8fe-52c8-4b63-b010-b02077fe02d6.jpg)
> 
> 我想压缩后保留dist目录以及子文件，但是不行

The same with me.

**Comment by sibiraj-s** [comment] 2023-07-01 14:57
You could do the following. onEnd accepts an array and guarantees order of execution.

```json
{
  "onEnd": [
    {
      "copy": [{ "source": "./dist", "destination": "./someFolder/dist" }]
    },
    {
      "archive": [
        { "source": "./someFolder/", "destination": "..somelocation.zip" }
      ]
    }
  ]
}
```

Closing this as there is a way to solve this.

**Closed by sibiraj-s** 2023-07-01 14:57 UTC
