### ISSUE TITLE
Unable to copy file at WebDAV location

### ISSUE THREAD

**Issue by RomanYegay** [gregnb/filemanager-webpack-plugin#92] opened 2021-01-31 15:53 UTC
## Config

Version 3.0.0-alpha.2 (works):

```js
new FileManagerPlugin({
  onEnd: {
    copy: AutoDeploy
      ? [
          {
            source: path.join(__dirname, "./dist/" + SiteRoot + AppConfig.WorkFolder + "/" + BundleFile + ".js"),
            destination: "\\\\" + SiteRoot + "@SSL\\DavWWWRoot" + AppConfig.WorkFolder.replace("/", "\\") + "\\",
          },
        ]
      : [{ source: "", destination: "" }],
  },
});
```

Version 3.1 (doesn't work):

```js
new FileManagerPlugin({
  events: {
    onEnd: {
      copy: AutoDeploy
        ? [
            {
              source: path.join(__dirname, "./dist/" + SiteRoot + AppConfig.WorkFolder + "/" + BundleFile + ".js"),
              destination: "\\\\" + SiteRoot + "@SSL\\DavWWWRoot" + AppConfig.WorkFolder.replace("/", "\\") + "\\",
            },
          ]
        : [{ source: "", destination: "" }],
    },
  },
});
```

## Issue

I am using plugin version 3.0.0-alpha.2 to copy files at prod server using WebDAV destination like "\\\\site.com@SSL\\DavWWWRoot\\folder\\", however after updrade to version 3.1 copy is failed by unknown reason.

## Your Environment

| Tech                       | Version    |
| -------------------------- | ---------- |
| filemanager-plugin-webpack | 3.1        |
| node                       | 12.2.0     |
| OS                         | Windows 10 |

**Comment by sibiraj-s** [comment] 2021-01-31 17:58
@RomanYegay Can you post the error message you get?

**Comment by RomanYegay** [comment] 2021-02-02 08:31
@sibiraj-s There was no error in console. However, after some research I've found that version 3.0.0-alpha.2 accepts improperly formatted WebDAV destination (like \\www.site.com@SSL\DavWWWRoot\level1/level2/level\), while version 3.1 doesn't. So this is mostly my fault, sorry.
 
PS: while testing found another issue, plugin can't copy absolute file names with glob pattern, i.e.
    source: './dist/' + SiteRoot + AppConfig.WorkFolder + '/') + BundleFile + '.{js,css}' will copy file, but
    source: 'C:/temp/test/dist/' + SiteRoot + AppConfig.WorkFolder + '/') + BundleFile + '.{js,css}' will not
In this case there is no any error message also.

**Comment by sibiraj-s** [comment] 2021-02-02 11:06
Cool. Glad the issue is fixed. I will close this one.

Regarding the other issue. I think it could be from here https://github.com/gregnb/filemanager-webpack-plugin/blob/master/src/actions/copy.js#L20. We are joining path with context. but actually we should check if path is absolute and then process. Feel free to open a new issue for this. I am occupied at the moment. I will work on this this weekend. meanwhile PR's are welcome.

**Closed by sibiraj-s** 2021-02-02 11:06 UTC
