### ISSUE TITLE
compiler.getInfrastructureLogger is not a function

### ISSUE THREAD

**Issue by 4550155** [gregnb/filemanager-webpack-plugin#97] opened 2021-04-28 08:58 UTC
ERROR  TypeError: compiler.getInfrastructureLogger is not a function

node_modules\filemanager-webpack-plugin\lib\index.js:581:30)
node_modules\webpack\lib\webpack.js:47:13)
node_modules\@vue\cli-service\lib\commands\build\index.js:192:5
node_modules\@vue\cli-service\lib\commands\build\index.js:191:10)
node_modules\@vue\cli-service\lib\commands\build\index.js:85:7

## Config

new FileManagerPlugin({
    events: {
      onStart: {
        delete: [path.join(__dirname, './dist.zip')]
      },
      onEnd: {
        archive: [{ source: path.join(__dirname, './dist'), destination: path.join(__dirname, './dist.zip') }]
      }
    }
  })

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |   4.0.0      |
| node                      |  v12.18.3       |
| npm                       |  v6.14.8       |
| webpack                |  v5.35.1       |
| OS                          |    windows 7 sp1     |

**Comment by sibiraj-s** [comment] 2021-04-28 10:07
Closing this. as it seems to be a duplicate of #91. See if the given solution here https://github.com/gregnb/filemanager-webpack-plugin/issues/91#issuecomment-818441476 works and continue the discussion there.

**Closed by sibiraj-s** 2021-04-28 10:07 UTC
