### ISSUE TITLE
使用过程报错

### ISSUE THREAD

**Issue by chenyjyoucan** [gregnb/filemanager-webpack-plugin#99] opened 2021-05-31 08:31 UTC
building for production.../Users/Desktop/17assess-FE/node_modules/_filemanager-webpack-plugin@5.0.0@filemanager-webpack-plugin/lib/index.js:579
    this.logger = compiler.getInfrastructureLogger(PLUGIN_NAME);
                           ^

TypeError: compiler.getInfrastructureLogger is not a function
    at FileManagerPlugin.apply (/Users/wenba/Desktop/17assess-FE/node_modules/_filemanager-webpack-plugin@5.0.0@filemanager-webpack-plugin/lib/index.js:579:28)
    at Compiler.apply (/Users/wenba/Desktop/17assess-FE/node_modules/_tapable@0.2.9@tapable/lib/Tapable.js:375:16)
    at webpack (/Users/wenba/Desktop/17assess-FE/node_modules/_webpack@3.12.0@webpack/lib/webpack.js:33:19)
    at /Users/wenba/Desktop/17assess-FE/build/build.js:27:3
    at next (/Users/wenba/Desktop/17assess-FE/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:83:7)
    at CB (/Users/wenba/Desktop/17assess-FE/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:119:9)
    at /Users/wenba/Desktop/17assess-FE/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:145:14

**Comment by sibiraj-s** [comment] 2021-06-03 07:03
Duplicate of #91. See https://github.com/gregnb/filemanager-webpack-plugin/issues/91#issuecomment-818441476

**Closed by sibiraj-s** 2021-06-03 07:03 UTC
